name: lhox
version: 0.0.0.0
license: GPL-3.0-or-later
author: Thales MG

dependencies:
  - base
  - containers
  - data-fix
  - generic-lens
  - microlens
  - microlens-mtl
  - mtl
  - raw-strings-qq
  - recursion-schemes
  - tasty
  - tasty-hunit
  - text

library:
  source-dirs: src

executables:
  lhox:
    main: Main.hs
    source-dirs: app
    dependencies:
      - lhox

tests:
  lhox-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - lhox
