name: lhox
version: 0.0.0.0
license: GPL-3.0-or-later
author: Thales MG

dependencies:
  - base
  - text
  - mtl

library:
  source-dirs: src

executables:
  lhox:
    main: Main.hs
    source-dirs: app
    dependencies:
      - lhox

tests:
  lhox-tests:
    main: MyLibTest.hs
    source-dirs: test
